### ISSUE TITLE
Unit only in km / s

### ISSUE THREAD

**Issue by titis14** [omnipresense/OPS241A_RasPiLCD#2]
Hello,
Thank you for your script, but I have a question, when displaying speed it changes to km / h, m / s, mph ... How do I make the speed only in km / h?
Thank you

**Comment by jimwhitfield** [comment]
Lines 165-171 exist only to demonstrate changing the speed.   
**Remove them.**
Since you want the default to be km/h, you should set the default accordingly.
In lines 15-17, observe:
```
Ops241A_Speed_Output_Units = ['US','UK','UM','UC']
Ops241A_Speed_Output_Units_lbl = ['mph','km/h','m/s','cm/s']
OPS_current_units = 3
```
Noting km/h is the [1]th item, set 
```OPS_current_units = 1```
(You can even do more cleanup of your copy of the code if you want, including simplifying this away from an array lookup to just using the "UK" command and displaying "km/h" directly.
